// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: url_shortening_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortenedUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
}

func (x *ShortenedUrl) Reset() {
	*x = ShortenedUrl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortening_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortenedUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenedUrl) ProtoMessage() {}

func (x *ShortenedUrl) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortening_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenedUrl.ProtoReflect.Descriptor instead.
func (*ShortenedUrl) Descriptor() ([]byte, []int) {
	return file_url_shortening_msg_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenedUrl) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type MainUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MainUrl string `protobuf:"bytes,1,opt,name=mainUrl,proto3" json:"mainUrl,omitempty"`
}

func (x *MainUrl) Reset() {
	*x = MainUrl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_url_shortening_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MainUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MainUrl) ProtoMessage() {}

func (x *MainUrl) ProtoReflect() protoreflect.Message {
	mi := &file_url_shortening_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MainUrl.ProtoReflect.Descriptor instead.
func (*MainUrl) Descriptor() ([]byte, []int) {
	return file_url_shortening_msg_proto_rawDescGZIP(), []int{1}
}

func (x *MainUrl) GetMainUrl() string {
	if x != nil {
		return x.MainUrl
	}
	return ""
}

var File_url_shortening_msg_proto protoreflect.FileDescriptor

var file_url_shortening_msg_proto_rawDesc = []byte{
	0x0a, 0x18, 0x75, 0x72, 0x6c, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x69, 0x6e, 0x67,
	0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2a,
	0x0a, 0x0c, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x23, 0x0a, 0x07, 0x4d, 0x61,
	0x69, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6e, 0x55, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6e, 0x55, 0x72, 0x6c, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_url_shortening_msg_proto_rawDescOnce sync.Once
	file_url_shortening_msg_proto_rawDescData = file_url_shortening_msg_proto_rawDesc
)

func file_url_shortening_msg_proto_rawDescGZIP() []byte {
	file_url_shortening_msg_proto_rawDescOnce.Do(func() {
		file_url_shortening_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_url_shortening_msg_proto_rawDescData)
	})
	return file_url_shortening_msg_proto_rawDescData
}

var file_url_shortening_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_url_shortening_msg_proto_goTypes = []interface{}{
	(*ShortenedUrl)(nil), // 0: pb.ShortenedUrl
	(*MainUrl)(nil),      // 1: pb.MainUrl
}
var file_url_shortening_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_url_shortening_msg_proto_init() }
func file_url_shortening_msg_proto_init() {
	if File_url_shortening_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_url_shortening_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortenedUrl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_url_shortening_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MainUrl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_url_shortening_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_url_shortening_msg_proto_goTypes,
		DependencyIndexes: file_url_shortening_msg_proto_depIdxs,
		MessageInfos:      file_url_shortening_msg_proto_msgTypes,
	}.Build()
	File_url_shortening_msg_proto = out.File
	file_url_shortening_msg_proto_rawDesc = nil
	file_url_shortening_msg_proto_goTypes = nil
	file_url_shortening_msg_proto_depIdxs = nil
}
